### PR TITLE
fix(xpath): Set xpath field type to text

### LINKED ISSUE #349: When creating a notice with a long Xpath - error 500
So when trying to input the following xpath (for the guerilla marketing):
> //*[@data-qa-id='adview_description_container']//text()[(contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'mandat postal') or contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'mandat cash') or contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'western union')) and not(contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'pas de mandat postal') or contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'mandat postal refusé') or contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'mandat cash refusé') or contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'western union refusé') or contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'pas de mandat cash') or contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'pas de western union') or contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'aucune demande de location avec acompte par mandat postal ou western Union') or contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'Refuse les paiements par western union') or contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'Pas de Reglement via Western Union') or contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'Pas de réservation par mandat') or contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'Les pionniers de la Western Union'))]

This error occurs:
image

I needed to modify the notice #1869

### PR DESCRIPTION
**Pull request by lutangar**
fix #349

### CODE REVIEW

File: migrations/Version20210416155713.php [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+ * Auto-generated Migration: Please modify to your needs!
+ */
+final class Version20210416155713 extends AbstractMigration
+{
+    public function up(Schema $schema): void
+    {
+        // this up() migration is auto-generated, please modify it to your needs
+        $this->abortIf('mysql' !== $this->connection->getDatabasePlatform()->getName(), 'Migration can only be executed safely on \'mysql\'.');
+
+        $this->addSql('ALTER TABLE matching_context CHANGE xpath xpath LONGTEXT DEFAULT NULL');
```
Comment (JalilArfaoui) [inline migrations/Version20210416155713.php:20]: We can `ALTER TABLE matching_context MODIFY xpath LONGTEXT DEFAULT NULL` since we’re not renaming the column

**Review by JalilArfaoui — APPROVED** [review]

File: migrations/Version20210416155713.php (hunk 1 above)
Comment (lutangar) [reply migrations/Version20210416155713.php:20]: Didn't know this one, I'll use it next time :+1:
